FROM tomcat:9-jdk8
LABEL NAME="vinod"
WORKDIR /game-of-life
ADD  https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war /usr/local/tomcat/webapps/game-of-lifegameoflife.war
EXPOSE 8080
